#!/bin/bash 
# file: _clean.sh 
# generated by metalsmith-cleanscript 
 
rm /Users/shane/projects/website/srcreigh.github.io/_clean.sh 
rm /Users/shane/projects/website/srcreigh.github.io/my-first-post/index.html 
rm /Users/shane/projects/website/srcreigh.github.io/my-fourth-post/index.html 
rm /Users/shane/projects/website/srcreigh.github.io/index.html 
rm /Users/shane/projects/website/srcreigh.github.io/my-second-post/index.html 
rm /Users/shane/projects/website/srcreigh.github.io/my-third-post/index.html 
 
rmdir /Users/shane/projects/website/srcreigh.github.io/my-third-post 
rmdir /Users/shane/projects/website/srcreigh.github.io/my-second-post 
rmdir /Users/shane/projects/website/srcreigh.github.io/my-fourth-post 
rmdir /Users/shane/projects/website/srcreigh.github.io/my-first-post 
