#!/bin/bash 
# file: clean.sh 
# generated by metalsmith-cleanscript 
 
rm /home/shane/projects/website/srcreigh.github.io/clean.sh 
rm /home/shane/projects/website/srcreigh.github.io/.first-post.md.swp 
rm /home/shane/projects/website/srcreigh.github.io/.fourth-post.md.swp 
rm /home/shane/projects/website/srcreigh.github.io/.index.md.swp 
rm /home/shane/projects/website/srcreigh.github.io/.second-post.md.swp 
rm /home/shane/projects/website/srcreigh.github.io/.third-post.md.swp 
rm /home/shane/projects/website/srcreigh.github.io/css/.reset.css.swp 
rm /home/shane/projects/website/srcreigh.github.io/css/reset.css 
rm /home/shane/projects/website/srcreigh.github.io/less/.main.less.swp 
rm /home/shane/projects/website/srcreigh.github.io/css/main.css 
rm /home/shane/projects/website/srcreigh.github.io/my-first-post/index.html 
rm /home/shane/projects/website/srcreigh.github.io/my-fourth-post/index.html 
rm /home/shane/projects/website/srcreigh.github.io/index.html 
rm /home/shane/projects/website/srcreigh.github.io/my-second-post/index.html 
rm /home/shane/projects/website/srcreigh.github.io/my-third-post/index.html 
 
rmdir /home/shane/projects/website/srcreigh.github.io/my-third-post 
rmdir /home/shane/projects/website/srcreigh.github.io/my-second-post 
rmdir /home/shane/projects/website/srcreigh.github.io/my-fourth-post 
rmdir /home/shane/projects/website/srcreigh.github.io/my-first-post 
rmdir /home/shane/projects/website/srcreigh.github.io/less 
rmdir /home/shane/projects/website/srcreigh.github.io/css 
